# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de71ef3ad9ce67334ea66f6e1ccb22c6543c5c89467bc458018a8ef44bfaff36313068d34d0a3642a5e610289b5090477bbd2fce06b2f5f220cc46ec872a81ce

test:
  secret_key_base: 9eb6b6fe11864456f1f6ebd33c8675d92d21a1f8631c6c69da632efc64084b4830a56062b27d8831f2a6911e30ed7ed4b6ea4f43bda45a5634ab42ed5093418f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
